import { useEffect, useMemo, useState } from "react";
import { Box, useTheme, useMediaQuery, alpha } from "@mui/material";
import { ComposableMap, Geographies, Geography, Marker } from "react-simple-maps";
import { geoMercator, geoPath, geoBounds } from "d3-geo";
import { useTranslation } from "../../utils/translations";
import SkeletonBlock from "../SkeletonBlock";

// A single chrome-less, full-bleed map filling the whole header section
// behind BOTH LeftSide and this component's own title — not a second map,
// the same instance just zoomed out and given the full section to render
// into instead of its own dedicated card. LeftSide's own card goes
// translucent (see LeftSide.jsx) so it reads as a glass panel floating over
// the same map rather than a separate boxed section next to/above it.
//
// Desktop splits LeftSide and the map side by side (a flex row), so the
// map is panned/cropped horizontally to land the country back where its
// old half-width card used to show it. Mobile stacks them vertically
// instead (LeftSide above, map below, in a single-column grid), so the
// same pan/crop trick runs on the vertical axis there — see the render
// below for both.
//
// Real, free, no-API-key map data: src/data/worldMap.topo.json, generated by
// client/scripts/buildMapData.js from Natural Earth (public domain) — no tile
// server, no key, no network call at runtime (bundled + dynamically imported
// so it's code-split rather than bloating the main bundle).
//
// Three layers, because this map is always zoomed to one country and a plain
// world-countries file has nothing to show at that zoom:
//   countries    — the 25 supported ones at 10m detail (their neighbours too),
//                  the rest of the world at 110m, since it is off-canvas here
//   subdivisions — provinces / wilayas / governorates of the 25, drawn as a
//                  mesh of internal borders only
//   lakes        — the region's water bodies, filled in the ocean tone
//   rivers       — the ones that define a country the way a border does (the
//                  Nile, the Tigris and Euphrates, the Niger), same tone
//   urbanAreas   — built-up footprints, as a faint wash showing where people
//                  are; the city dots say where the posts are
// The build script explains how the resolution is budgeted; the short version
// is that this file is smaller than the single-layer countries-50m.json it
// replaced while giving the country on screen several times its detail.
//
// Deliberately NOT mirrored for RTL: an actual world map has to stay
// geographically accurate regardless of reading direction — real maps on
// Arabic sites are never horizontally flipped. Only the surrounding chrome
// (title, legend) follows the usual RTL/logical-property rules.
//
// Zoom math note: react-simple-maps' projectionConfig only forwards
// center/scale/rotate/parallels to the underlying d3 projection — it always
// hardcodes translate to the canvas center (see its makeProjection()), so
// d3's usual fitExtent() (which computes scale AND a possibly-off-center
// translate) can't be used directly; passing fitExtent's translate is
// silently ignored, which very nearly shipped a broken zoom. Instead:
// center on the country's bounding-box midpoint (not its true centroid —
// those differ for an irregular shape, and only the bbox midpoint lands the
// bbox itself in the middle of a fixed-translate canvas), then solve for
// the scale that fits that bbox into the padded target area by measuring
// the projected bounds at a reference scale of 1 and dividing. Same
// constraint is why the country can't be pinned to one side of the wide
// desktop canvas the way "same place" might suggest — translate always
// lands it dead-center of whatever canvas size we give the map, so a wider
// canvas with more padding just reads as "more of the world around it,"
// not "shifted to the right."
const ISO2_TO_NUMERIC = {
  AE: "784", BH: "048", CF: "140", TD: "148", KM: "174", DZ: "012",
  DJ: "262", EG: "818", IQ: "368", JO: "400", KW: "414", LB: "422",
  LY: "434", MA: "504", ML: "466", MR: "478", NE: "562", OM: "512",
  PS: "275", QA: "634", SA: "682", SO: "706", SD: "729", SY: "760",
  TN: "788",
};

// Every city dot is the same small size. The dots used to be a
// proportional symbol (radius scaled by the city's all-time post count),
// which made a busy city's marker swallow its neighbours and read as an
// arbitrary difference in importance at a glance; the per-city numbers are
// carried by the "+N today" badges instead. Matches mobile's
// WorldActivityMap.js.
const CITY_DOT_RADIUS = 4;

const WorldActivityMap = ({
  worldActivity,
  cityActivity,
  currentCountryCode,
  countriesByCode,
  isLoading,
  hideTitle = false,
  titleOffsetTop = 0,
}) => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const { currentLanguage } = useTranslation();
  const isRTL = currentLanguage === "ar";
  const [mapLayers, setMapLayers] = useState(null);
  const geoFeatures = mapLayers?.countries || null;

  const ink = theme.custom.color.ink;
  const panel = theme.custom.color.surfaceRaised;
  const brand = theme.custom.color.brandPrimary;
  // What the containers behind this map paint for the sea (Dash.js and
  // WelcomePage both use surfaceBase); lakes reuse it so inland water matches.
  const sea = theme.custom.color.surfaceBase;
  const isDark = theme.palette.mode === "dark";

  useEffect(() => {
    let cancelled = false;
    Promise.all([import("../../data/worldMap.topo.json"), import("topojson-client")]).then(
      ([topoModule, topojsonClient]) => {
        if (cancelled) return;
        const topo = topoModule.default;
        setMapLayers({
          countries: topojsonClient.feature(topo, topo.objects.countries).features,
          // Internal borders only: the `a !== b` filter keeps arcs shared by two
          // provinces and drops every arc with just one neighbour — the coast
          // and the national outline, which the countries layer already draws.
          // Because the country shapes were built as the union of these same
          // provinces, this is the identical arc, not a second line beside it.
          subdivisions: topojsonClient.mesh(topo, topo.objects.subdivisions, (a, b) => a !== b),
          // No filter on the river mesh — every arc is wanted, and mesh is
          // still the right call over feature() because it emits each shared
          // arc once and yields a single node instead of a hundred.
          rivers: topojsonClient.mesh(topo, topo.objects.rivers),
          // Kept as whole FeatureCollections: d3's geoPath renders one straight
          // into a single `d`, so each of these layers is one node too.
          lakes: topojsonClient.feature(topo, topo.objects.lakes),
          urbanAreas: topojsonClient.feature(topo, topo.objects.urbanAreas),
        });
      }
    );
    return () => {
      cancelled = true;
    };
  }, []);

  const activityByNumericId = useMemo(() => {
    const map = new Map();
    (worldActivity || []).forEach(({ code, count }) => {
      const numericId = ISO2_TO_NUMERIC[code];
      if (numericId) map.set(numericId, { code, count });
    });
    return map;
  }, [worldActivity]);

  const maxCount = useMemo(
    () => (worldActivity || []).reduce((m, row) => Math.max(m, row.count || 0), 0) || 1,
    [worldActivity]
  );

  const cities = useMemo(() => (Array.isArray(cityActivity) ? cityActivity : []), [cityActivity]);

  // Cities that got at least one new post today — the only ones that get a
  // "+N" badge. todayCount comes from the same cityActivity aggregation as
  // `count`, over the same server-local day window the header's "+N today"
  // stats use, so the two never disagree. Falls back to no badges at all
  // (rather than badging totals) when talking to a server that predates the
  // field, since a total-count badge labelled "+N" would read as "N new".
  const citiesWithNewToday = useMemo(() => cities.filter((c) => (c.todayCount || 0) > 0), [cities]);

  // Post-count badge above each city dot ("+12"). Sized in SVG user units
  // rather than CSS, so it scales with the map exactly like the dots and
  // city labels do. Width is approximated from the label's character count
  // (no text metrics available at render time in SVG) — 6.2 units per glyph
  // at fontSize 11 bold, plus horizontal padding, floored so a single-digit
  // badge still reads as a pill rather than a circle.
  const BADGE_HEIGHT = 18;
  const BADGE_FONT_SIZE = 11;
  const badgeWidth = (label) => Math.max(26, label.length * 6.2 + 12);
  const badgeText = theme.palette.getContrastText(brand);

  const currentNumericId = currentCountryCode ? ISO2_TO_NUMERIC[currentCountryCode] : null;

  const currentFeature = useMemo(() => {
    if (!geoFeatures || !currentNumericId) return null;
    return geoFeatures.find((f) => f.id === currentNumericId) || null;
  }, [geoFeatures, currentNumericId]);

  // Mobile: square reference canvas, kept tightly zoomed (the vertical
  // crop below handles positioning, not this). Desktop: wide canvas
  // matching the full header's rough proportions, zoomed out a lot further
  // so the surrounding world reads as a backdrop, not a crop.
  const MAP_WIDTH = isMobile ? 520 : 1100;
  const mapHeight = isMobile ? 520 : 480;

  const mapView = useMemo(() => {
    if (!currentFeature) return { center: [15, 20], scale: 220 };
    const padding = isMobile ? 60 : 70;
    const [[minLon, minLat], [maxLon, maxLat]] = geoBounds(currentFeature);
    const center = [(minLon + maxLon) / 2, (minLat + maxLat) / 2];
    const reference = geoMercator().center(center).translate([MAP_WIDTH / 2, mapHeight / 2]).scale(1);
    const [[x0, y0], [x1, y1]] = geoPath(reference).bounds(currentFeature);
    const scale = Math.min((MAP_WIDTH - padding * 2) / Math.max(x1 - x0, 0.001), (mapHeight - padding * 2) / Math.max(y1 - y0, 0.001));
    return { center, scale };
  }, [currentFeature, MAP_WIDTH, mapHeight, isMobile]);

  // The projection react-simple-maps builds internally, rebuilt here so the
  // subdivision mesh and the lakes can be drawn as plain <path> nodes in the
  // same coordinate space as <Geography>. Safe to reconstruct rather than
  // guess at: projectionConfig forwards center/scale verbatim and translate is
  // always the canvas centre (see the zoom-math note above).
  const mapPath = useMemo(
    () =>
      geoPath(
        geoMercator()
          .center(mapView.center)
          .scale(mapView.scale)
          .translate([MAP_WIDTH / 2, mapHeight / 2])
      ),
    [mapView, MAP_WIDTH, mapHeight]
  );

  // Projected once per view, not per render: the subdivision mesh is a single
  // path with tens of thousands of points, and this component re-renders on
  // every theme, language and hover change.
  const subdivisionsPath = useMemo(
    () => (mapLayers?.subdivisions ? mapPath(mapLayers.subdivisions) : null),
    [mapLayers, mapPath]
  );
  const riversPath = useMemo(
    () => (mapLayers?.rivers ? mapPath(mapLayers.rivers) : null),
    [mapLayers, mapPath]
  );
  const lakesPath = useMemo(
    () => (mapLayers?.lakes ? mapPath(mapLayers.lakes) : null),
    [mapLayers, mapPath]
  );
  const urbanPath = useMemo(
    () => (mapLayers?.urbanAreas ? mapPath(mapLayers.urbanAreas) : null),
    [mapLayers, mapPath]
  );

  if (isLoading) {
    return <SkeletonBlock radius={0} sx={{ width: "100%", height: "100%" }} />;
  }

  const mapNode = geoFeatures ? (
    <ComposableMap
      width={MAP_WIDTH}
      height={mapHeight}
      projection="geoMercator"
      projectionConfig={{ center: mapView.center, scale: mapView.scale }}
      style={{ width: "100%", height: "100%" }}
    >
      <Geographies geography={geoFeatures}>
        {({ geographies }) =>
          geographies.map((geo) => {
            const entry = activityByNumericId.get(geo.id);
            const isCurrent = geo.id === currentNumericId;
            const baseFill = entry
              ? alpha(brand, 0.22 + (entry.count / maxCount) * 0.68)
              : alpha(ink, isDark ? 0.14 : 0.08);
            return (
              <Geography
                key={geo.rsmKey}
                geography={geo}
                style={{
                  default: {
                    fill: baseFill,
                    stroke: isCurrent ? brand : alpha(panel, isDark ? 0.4 : 0.8),
                    strokeWidth: isCurrent ? 1.6 : 0.5,
                    outline: "none",
                  },
                  hover: {
                    fill: entry ? alpha(brand, 0.9) : alpha(ink, isDark ? 0.22 : 0.16),
                    stroke: isCurrent ? brand : alpha(panel, isDark ? 0.4 : 0.8),
                    strokeWidth: isCurrent ? 1.6 : 0.5,
                    outline: "none",
                    cursor: "pointer",
                  },
                  pressed: { outline: "none" },
                }}
              />
            );
          })
        }
      </Geographies>

      {/* Built-up areas, under everything else that sits on the country fill:
          a wash, not a shape — it should register as "this part is populated"
          without ever competing with the city dots, which are the only thing on
          this map carrying real data. */}
      {urbanPath && (
        <path d={urbanPath} fill={alpha(ink, isDark ? 0.18 : 0.12)} pointerEvents="none" />
      )}

      {/* Provinces / wilayas / governorates of the supported countries, as one
          mesh path rather than per-province shapes — the country underneath is
          the interactive unit, and a mesh is a single node with no fill to
          double up on the fills below it. Deliberately faint: it is texture
          telling you the country is a real place with regions in it, not
          information the dashboard is asking anyone to read. */}
      {subdivisionsPath && (
        <path
          d={subdivisionsPath}
          fill="none"
          stroke={alpha(panel, isDark ? 0.35 : 0.7)}
          strokeWidth={0.4}
          strokeLinejoin="round"
          pointerEvents="none"
        />
      )}

      {/* Lakes, in the same tone the container paints behind the map for the
          sea (see Dash.js) — so inland water reads as water rather than as a
          hole punched in the country. */}
      {lakesPath && <path d={lakesPath} fill={sea} stroke="none" pointerEvents="none" />}

      {/* Rivers, in the same tone as the lakes and the sea, stroked rather than
          filled. Thin enough to read as water rather than as another border. */}
      {riversPath && (
        <path
          d={riversPath}
          fill="none"
          stroke={sea}
          strokeWidth={0.6}
          strokeLinecap="round"
          strokeLinejoin="round"
          pointerEvents="none"
        />
      )}

      {/* City markers — uniform small dots (see CITY_DOT_RADIUS) layered on
          top of the country fill. Panel-filled with a brand stroke so they
          read as solid pins regardless of the fill tone beneath them;
          labels get a panel-colored text outline (paintOrder="stroke") for
          the same reason, rather than a background pill shape. */}
      {cities.map((city, index) => (
        <Marker key={`${city.name}-${index}`} coordinates={[city.lon, city.lat]}>
          <circle r={CITY_DOT_RADIUS} fill={panel} stroke={brand} strokeWidth={2} />
          <text
            y={CITY_DOT_RADIUS + 12}
            textAnchor="middle"
            fontSize={10}
            fontWeight={600}
            fill={ink}
            stroke={panel}
            strokeWidth={3}
            paintOrder="stroke"
            pointerEvents="none"
          >
            {city.name}
          </text>
        </Marker>
      ))}

      {/* Today's-new-posts badges, in their own pass after all dots/labels
          so a badge is never overlapped by a neighbouring city's marker
          drawn later. Only cities with activity today are badged — now that
          every dot is the same size, this is the only per-city number the
          map shows. */}
      {citiesWithNewToday.map((city, index) => {
        const label = `+${city.todayCount}`;
        const width = badgeWidth(label);
        // Sits just clear of the dot's stroke, close enough to read as part
        // of the same marker rather than a floating label.
        const anchorY = -(CITY_DOT_RADIUS + 1);
        return (
          <Marker key={`${city.name}-${index}-count`} coordinates={[city.lon, city.lat]}>
            <g pointerEvents="none">
              {/* Panel-colored halo, same trick the city label uses: keeps
                  the pill legible over a saturated country fill without
                  needing an opaque plate behind it. */}
              <rect
                x={-width / 2}
                y={anchorY - BADGE_HEIGHT}
                width={width}
                height={BADGE_HEIGHT}
                rx={BADGE_HEIGHT / 2}
                fill={brand}
                stroke={panel}
                strokeWidth={2}
              />
              <text
                x={0}
                y={anchorY - BADGE_HEIGHT / 2}
                textAnchor="middle"
                dominantBaseline="central"
                fontSize={BADGE_FONT_SIZE}
                fontWeight={700}
                fill={badgeText}
              >
                {label}
              </text>
            </g>
          </Marker>
        );
      })}
    </ComposableMap>
  ) : (
    <Box sx={{ width: "100%", height: "100%", backgroundColor: alpha(ink, 0.05) }} />
  );

  const legendSwatch = (
    <Box
      sx={{
        width: 48,
        height: 7,
        borderRadius: 4,
        background: `linear-gradient(${isRTL ? "to left" : "to right"}, ${alpha(brand, 0.2)}, ${alpha(brand, 0.95)})`,
      }}
    />
  );

  // Chrome-less full-bleed map. Dash.js renders this absolutely positioned
  // to fill the whole header section (behind LeftSide too — on mobile
  // that's LeftSide's own row plus a reserved spacer row below it; on
  // desktop it's the whole side-by-side row), so here it just needs to
  // fill 100% of whatever box it's given.
  //
  // Pan/crop for "same place as before": react-simple-maps always renders
  // the projection centered on its own canvas (translate can't be
  // customized — see the note above), so the chosen country would otherwise
  // land dead-center of the full header and get hidden behind LeftSide. To
  // put it back where its old dedicated card used to show it, the map is
  // rendered oversized on the axis LeftSide pushes it along, then shifted
  // so ITS center — always where the country renders — lands at roughly
  // the old card's center; Dash.js's header container clips the overflow.
  // Desktop: LeftSide sits beside the map (a flex row), so the crop runs
  // horizontally, landing the country ~75% across from the logical start
  // (~25% in from the end), mirroring the old half-width card. Mobile:
  // LeftSide sits above the map (a single-column stack), so the crop runs
  // vertically instead, landing the country ~81% down (roughly where the
  // old square card's center sat below LeftSide's — measured taller — stats
  // panel). The enlarged height (271%) is chosen as roughly
  // totalHeaderHeight/spacerHeight, so the vertical CSS stretch on the
  // visible crop works out the same as when the map had its own ~37%-tall
  // dedicated card — same apparent zoom, just repositioned. The CSS stretch
  // (100% of an already-oversized box) scales the SVG non-uniformly the
  // same way it always did pre-crop (viewBox aspect ratio never matched the
  // container's), so the zoom/padding math above is untouched by this — it
  // still targets the same on-canvas fit as before.
  const mapCropSx = isMobile
    ? { position: "absolute", insetInlineStart: 0, width: "100%", top: "-54%", height: "271%" }
    : { position: "absolute", top: 0, bottom: 0, insetInlineStart: "-7.5%", width: "165%" };

  // titleOffsetTop: lets a caller with extra chrome above this component
  // (e.g. WelcomePage's language/mode controls, which sit inside the same
  // full-bleed section on desktop) push the desktop title down clear of it,
  // without affecting Dash.js's own header, which has no such chrome and
  // never passes this prop (defaults to 0 — pixel-identical to before).
  const titleOverlaySx = isMobile
    ? { position: "absolute", top: "63%", insetInlineStart: 0, insetInlineEnd: 0, display: "flex", flexDirection: "column", alignItems: "center", gap: 1 }
    : { position: "absolute", top: 24 + titleOffsetTop, insetInlineEnd: 32, insetInlineStart: "52%", display: "flex", flexDirection: "column", alignItems: "center", gap: 1 };

  return (
    <Box sx={{ width: "100%", height: "100%", position: "relative", overflow: "hidden" }}>
      <Box sx={mapCropSx}>{mapNode}</Box>
      {!hideTitle && (
        <Box sx={titleOverlaySx}>
          {legendSwatch}
        </Box>
      )}
    </Box>
  );
};

export default WorldActivityMap;
