// Single source of truth for the app's native/build config. android/ and ios/ are
// Continuous Native Generation output (gitignored, regenerated by `expo prebuild` /
// every EAS build) - never hand-edit the native project directly, change it here.

// EAS Build sets this env var during cloud builds (matches the eas.json profile name).
// `development`/`preview` build a raw universal APK for direct install (see BUILD.md) -
// restricting to arm64-v8a (the only ABI virtually any device sold since ~2019 needs)
// cuts that APK's native-library payload roughly 4x. `production` builds an AAB for the
// Play Store, which already splits per-device server-side, so it's left unfiltered.
const isInternalTestBuild = ["development", "preview"].includes(process.env.EAS_BUILD_PROFILE);

export default {
  expo: {
    name: "Mafqoudat",
    slug: "mafqoudat",
    version: "1.0.0",
    // Without an explicit policy, expo-updates (installed but not otherwise configured -
    // this app doesn't use EAS Update/OTA) defaults a config-driven (CNG) project to a
    // "fingerprint" runtime version. Expo Go's dev server can only resolve the
    // "sdkVersion" policy ("Unable to determine redirect location for runtime 'custom'"
    // otherwise) - pinning this is what makes `expo start --go` work again.
    runtimeVersion: {
      policy: "sdkVersion"
    },
    updates: {
      enabled: false
    },
    orientation: "portrait",
    icon: "./assets/icon.png",
    userInterfaceStyle: "automatic",
    splash: {
      image: "./assets/splash.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff"
    },
    assetBundlePatterns: ["**/*"],
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.mafqoudat.app",
      buildNumber: "1",
      infoPlist: {
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to upload images for lost and found items.",
        NSCameraUsageDescription: "This app needs access to your camera to take photos for lost and found items.",
        NSLocationWhenInUseUsageDescription: "This app uses your location to help you find lost items in your area."
      },
      config: {
        usesNonExemptEncryption: false
      },
      // Universal Links: lets a tap on https://(www.)mafqoudat.com/dash/posts/:id
      // open straight into PostDetailScreen (see App.js's `linking` config)
      // instead of Safari, on a device with the app installed. Requires
      // https://www.mafqoudat.com/.well-known/apple-app-site-association to
      // list this app's real Team ID - see mobile/UNIVERSAL_LINKS_SETUP.md -
      // and only takes effect from a fresh native build (`eas build`), never
      // an OTA update.
      associatedDomains: [
        "applinks:mafqoudat.com",
        "applinks:www.mafqoudat.com"
      ]
    },
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: "#ffffff"
      },
      package: "com.mafqoudat.app",
      versionCode: 1,
      permissions: [
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION"
      ],
      intentFilters: [
        {
          action: "VIEW",
          autoVerify: true,
          data: [
            {
              scheme: "mafqoudat",
              host: "auth",
              pathPrefix: "/callback"
            }
          ],
          category: ["BROWSABLE", "DEFAULT"]
        },
        // App Links: Android's counterpart to iOS's associatedDomains above -
        // same feature, same caveats (needs the real SHA-256 signing
        // fingerprint in assetlinks.json, see
        // mobile/UNIVERSAL_LINKS_SETUP.md; needs a fresh native build).
        // pathPrefix also matches the bare "/dash/posts" listing URL, which
        // isn't registered in App.js's `linking.config.screens` - opening
        // that one is a harmless no-op, not a crash.
        {
          action: "VIEW",
          autoVerify: true,
          data: [
            {
              scheme: "https",
              host: "mafqoudat.com",
              pathPrefix: "/dash/posts"
            },
            {
              scheme: "https",
              host: "www.mafqoudat.com",
              pathPrefix: "/dash/posts"
            }
          ],
          category: ["BROWSABLE", "DEFAULT"]
        }
      ]
    },
    web: {
      favicon: "./assets/favicon.png"
    },
    plugins: [
      [
        "expo-image-picker",
        {
          photosPermission: "The app accesses your photos to let you share them for lost and found items."
        }
      ],
      // Required by expo-web-browser v15+ (config plugin sets up the native
      // browser-session support used by the legacy Google auth fallback flow).
      "expo-web-browser",
      // Required by expo-secure-store v15+ (config plugin sets Android's
      // faceIDPermission / no-op iOS entries; no custom options needed here).
      "expo-secure-store",
      // APK/AAB size: enables R8 code shrinking + resource shrinking on every Android
      // release build (preview APK and production AAB alike - neither was minified
      // before), and restricts native libs to arm64-v8a on internal-test builds only
      // (see isInternalTestBuild above).
      [
        "expo-build-properties",
        {
          android: {
            enableProguardInReleaseBuilds: true,
            enableShrinkResourcesInReleaseBuilds: true,
            ...(isInternalTestBuild ? { buildArchs: ["arm64-v8a"] } : {})
          }
        }
      ]
    ],
    // EXPO_PUBLIC_-prefixed vars are inlined directly into the JS bundle at build time
    // (see src/config/api.js, which reads process.env.EXPO_PUBLIC_* directly) - mirroring
    // them into `extra` as well makes them visible in `expo config` / EAS build logs /
    // the build manifest for debugging, without adding a second runtime access path.
    extra: {
      apiUrl: process.env.EXPO_PUBLIC_API_URL,
      googleWebClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
      googleIosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
      googleAndroidClientId: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,
      useNativeGoogleAuth: process.env.EXPO_PUBLIC_USE_NATIVE_GOOGLE_AUTH,
      webBaseUrl: process.env.EXPO_PUBLIC_WEB_BASE_URL,
      eas: {
        // @mafnacer/mafqoudat - created via `eas init`:
        // https://expo.dev/accounts/mafnacer/projects/mafqoudat
        projectId: "0af1537e-6e29-4127-badc-c7f16884e198"
      }
    },
    scheme: "mafqoudat"
  }
};
