// Single source of truth for the app's native/build config. android/ and ios/ are
// Continuous Native Generation output (gitignored, regenerated by `expo prebuild` /
// every EAS build) - never hand-edit the native project directly, change it here.
export default {
  expo: {
    name: "Mafqoudat",
    slug: "mafqoudat",
    version: "1.0.0",
    // Without an explicit policy, expo-updates (installed but not otherwise configured -
    // this app doesn't use EAS Update/OTA) defaults a config-driven (CNG) project to a
    // "fingerprint" runtime version. Expo Go's dev server can only resolve the
    // "sdkVersion" policy ("Unable to determine redirect location for runtime 'custom'"
    // otherwise) - pinning this is what makes `expo start --go` work again.
    runtimeVersion: {
      policy: "sdkVersion"
    },
    updates: {
      enabled: false
    },
    orientation: "portrait",
    icon: "./assets/icon.png",
    userInterfaceStyle: "light",
    splash: {
      image: "./assets/splash.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff"
    },
    assetBundlePatterns: ["**/*"],
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.mafqoudat.app",
      buildNumber: "1",
      infoPlist: {
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to upload images for lost and found items.",
        NSCameraUsageDescription: "This app needs access to your camera to take photos for lost and found items.",
        NSLocationWhenInUseUsageDescription: "This app uses your location to help you find lost items in your area."
      },
      config: {
        usesNonExemptEncryption: false
      }
    },
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: "#ffffff"
      },
      package: "com.mafqoudat.app",
      versionCode: 1,
      permissions: [
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION"
      ],
      intentFilters: [
        {
          action: "VIEW",
          autoVerify: true,
          data: [
            {
              scheme: "mafqoudat",
              host: "auth",
              pathPrefix: "/callback"
            }
          ],
          category: ["BROWSABLE", "DEFAULT"]
        }
      ]
    },
    web: {
      favicon: "./assets/favicon.png"
    },
    plugins: [
      [
        "expo-image-picker",
        {
          photosPermission: "The app accesses your photos to let you share them for lost and found items."
        }
      ]
    ],
    // EXPO_PUBLIC_-prefixed vars are inlined directly into the JS bundle at build time
    // (see src/config/api.js, which reads process.env.EXPO_PUBLIC_* directly) - mirroring
    // them into `extra` as well makes them visible in `expo config` / EAS build logs /
    // the build manifest for debugging, without adding a second runtime access path.
    extra: {
      apiUrl: process.env.EXPO_PUBLIC_API_URL,
      googleWebClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
      googleIosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
      googleAndroidClientId: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,
      useNativeGoogleAuth: process.env.EXPO_PUBLIC_USE_NATIVE_GOOGLE_AUTH,
      webBaseUrl: process.env.EXPO_PUBLIC_WEB_BASE_URL,
      eas: {
        // Replaced automatically the first time `eas init` (or `eas build:configure`)
        // runs against this project - see BUILD.md. Every `eas build`/`eas submit`
        // invocation before that will fail until this is a real project id.
        projectId: "REPLACE_WITH_EAS_PROJECT_ID"
      }
    },
    scheme: "mafqoudat"
  }
};
