// Single source of truth for the app's native/build config. android/ and ios/ are
// Continuous Native Generation output (gitignored, regenerated by `expo prebuild` /
// every EAS build) - never hand-edit the native project directly, change it here.

import fs from "fs";

// EAS Build sets this env var during cloud builds (matches the eas.json profile name).
// `development`/`preview` build a raw universal APK for direct install (see BUILD.md) -
// restricting to arm64-v8a (the only ABI virtually any device sold since ~2019 needs)
// cuts that APK's native-library payload roughly 4x. `production` builds an AAB for the
// Play Store, which already splits per-device server-side, so it's left unfiltered.
const isInternalTestBuild = ["development", "preview"].includes(process.env.EAS_BUILD_PROFILE);

// EAS exposes a file secret as a path in the environment; a local prebuild uses
// the file in this directory if someone has put one there. Resolved to null
// when neither exists - see the android.googleServicesFile note below.
const localGoogleServices = "./google-services.json";
const googleServicesFile = process.env.GOOGLE_SERVICES_JSON
  || (fs.existsSync(localGoogleServices) ? localGoogleServices : null);

export default {
  expo: {
    name: "Mafqoudat",
    slug: "mafqoudat",
    version: "1.0.0",
    // Without an explicit policy, expo-updates (installed but not otherwise configured -
    // this app doesn't use EAS Update/OTA) defaults a config-driven (CNG) project to a
    // "fingerprint" runtime version. Expo Go's dev server can only resolve the
    // "sdkVersion" policy ("Unable to determine redirect location for runtime 'custom'"
    // otherwise) - pinning this is what makes `expo start --go` work again.
    runtimeVersion: {
      policy: "sdkVersion"
    },
    updates: {
      enabled: false
    },
    orientation: "portrait",
    icon: "./assets/icon.png",
    userInterfaceStyle: "automatic",
    splash: {
      image: "./assets/splash.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff"
    },
    assetBundlePatterns: ["**/*"],
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.mafqoudat.app",
      // Omitted for the same reason as android.versionCode above - EAS owns it
      // under `appVersionSource: "remote"`.
      // Only the photo-library string is declared. The camera and location
      // strings that used to sit here described features this app does not
      // have: nothing calls launchCameraAsync, and there is no location API in
      // the project at all (the "location" on a post is free text the user
      // types). A usage string for a capability the app never exercises is a
      // review question with no good answer.
      infoPlist: {
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to upload images for lost and found items."
      },
      config: {
        usesNonExemptEncryption: false
      },
      // Universal Links: lets a tap on https://(www.)mafqoudat.com/dash/posts/:id
      // open straight into PostDetailScreen (see App.js's `linking` config)
      // instead of Safari, on a device with the app installed. Requires
      // https://www.mafqoudat.com/.well-known/apple-app-site-association to
      // list this app's real Team ID - see mobile/UNIVERSAL_LINKS_SETUP.md -
      // and only takes effect from a fresh native build (`eas build`), never
      // an OTA update.
      associatedDomains: [
        "applinks:mafqoudat.com",
        "applinks:www.mafqoudat.com"
      ]
    },
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        // Themed icons (Android 13+): without this layer the launcher falls
        // back to the full-colour icon while every other icon on the home
        // screen follows the wallpaper palette.
        monochromeImage: "./assets/adaptive-icon-monochrome.png",
        backgroundColor: "#ffffff"
      },
      package: "com.mafqoudat.app",
      // Firebase config for FCM, which is how a push notification physically
      // reaches an Android device (Expo's push service is the sender in front
      // of it, not a replacement for it). See mobile/PUSH_NOTIFICATIONS.md.
      //
      // Spread rather than set unconditionally: naming a file that is not there
      // fails the build outright, and this one is deliberately not in git (it
      // is per-Firebase-project, and is supplied to EAS as the file secret
      // GOOGLE_SERVICES_JSON). Until it exists, builds keep working exactly as
      // before and push is the only thing that does not work.
      ...(googleServicesFile ? { googleServicesFile } : {}),
      // No versionCode here on purpose: eas.json sets
      // `cli.appVersionSource: "remote"`, so EAS owns the build number and the
      // production profile auto-increments it. A hardcoded 1 in this file is
      // ignored by every EAS build, and the moment anyone flipped the source
      // back to "local" it would start uploading duplicate version codes, which
      // Play rejects. Run `eas build:version:set` to change it instead.
      // Google Play requires every requested permission to be necessary for a
      // feature the app actually has. This app needs none of the dangerous ones
      // in its own right: it talks to the network (INTERNET is added by React
      // Native itself) and picks photos through the OS photo picker, which
      // grants access to the selected item only and requires no permission.
      //
      // POST_NOTIFICATIONS (Android 13+) is the one runtime permission the app
      // does request, and it is added by the expo-notifications plugin rather
      // than listed here. It backs a feature that exists - match alerts
      // delivered while the app is closed - is requested in context rather than
      // at launch (see src/utils/pushNotifications.js), and needs no Play
      // Console declaration, unlike the alarm permissions blocked below.
      //
      // The two location permissions that used to be listed here were never
      // backed by any code - there is no expo-location dependency and no
      // geolocation call anywhere in src/. A post's location is free text the
      // user types. Requesting location for a feature that does not exist would
      // have forced a Location Permissions declaration in the Play Console that
      // could not be answered truthfully.
      permissions: [],
      // Permissions listed above are *added*; these are *removed*. Libraries
      // merge their own <uses-permission> entries into the final manifest
      // regardless of the list above, so dropping a permission from `permissions`
      // is not enough on its own - it has to be blocked.
      //
      // expo-image-picker's AndroidManifest declares CAMERA (for
      // launchCameraAsync, which this app never calls) and the two legacy
      // storage permissions (which only requestMediaLibraryPermissionsAsync
      // needed - see the note in components/PostForm.js, which no longer calls
      // it). CAMERA and RECORD_AUDIO are additionally blocked by the plugin
      // options below; listing them here too keeps the full set readable in one
      // place and is harmless, since both paths emit the same removal.
      //
      // expo-notifications brings its own set, all of which exist for *local*
      // notifications - scheduling one for later, and restoring the schedule
      // after a reboot. This app only ever receives remote pushes from the
      // server, schedules nothing, and so needs none of them. Two of the three
      // matter beyond tidiness: SCHEDULE_EXACT_ALARM and USE_EXACT_ALARM are
      // Google Play "sensitive" permissions that force a Play Console
      // declaration, and there is no truthful declaration to make for a feature
      // the app does not have.
      blockedPermissions: [
        "android.permission.CAMERA",
        "android.permission.RECORD_AUDIO",
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.SCHEDULE_EXACT_ALARM",
        "android.permission.USE_EXACT_ALARM",
        "android.permission.RECEIVE_BOOT_COMPLETED"
      ],
      intentFilters: [
        // The OAuth callback bridge. No autoVerify here, deliberately: Android
        // App Links verification applies only to http/https filters, and from
        // Android 12 the verification agent evaluates every autoVerify filter in
        // the manifest as one batch - a non-web filter carrying the flag can
        // sink verification for the real https filter below it. The custom
        // scheme needs no verification anyway; it is claimed by declaration.
        {
          action: "VIEW",
          data: [
            {
              scheme: "mafqoudat",
              host: "auth",
              pathPrefix: "/callback"
            }
          ],
          category: ["BROWSABLE", "DEFAULT"]
        },
        // App Links: Android's counterpart to iOS's associatedDomains above -
        // same feature, same caveats (needs the real SHA-256 signing
        // fingerprint in assetlinks.json, and that has to be the Play App
        // Signing key rather than the upload key, since Play re-signs the AAB;
        // see mobile/UNIVERSAL_LINKS_SETUP.md. Needs a fresh native build).
        //
        // pathPattern rather than pathPrefix: App.js's
        // `linking.config.screens` only registers "dash/posts/:id", so a prefix
        // match also claimed the bare "/dash/posts" listing URL and opened the
        // app on a link it cannot resolve. "/dash/posts/.*" requires something
        // after the slash, which matches what the iOS side already declares in
        // .well-known/apple-app-site-association ("/dash/posts/*").
        {
          action: "VIEW",
          autoVerify: true,
          data: [
            {
              scheme: "https",
              host: "mafqoudat.com",
              pathPattern: "/dash/posts/.*"
            },
            {
              scheme: "https",
              host: "www.mafqoudat.com",
              pathPattern: "/dash/posts/.*"
            }
          ],
          category: ["BROWSABLE", "DEFAULT"]
        }
      ]
    },
    web: {
      favicon: "./assets/favicon.png"
    },
    plugins: [
      [
        "expo-image-picker",
        {
          photosPermission: "The app accesses your photos to let you share them for lost and found items.",
          // Both `false` values are load-bearing, not cosmetic. The plugin adds
          // RECORD_AUDIO to the Android manifest unless microphonePermission is
          // explicitly false - so this app was shipping a microphone permission
          // it has no feature for. Setting either to false also makes the plugin
          // block that permission on Android and skip the matching iOS usage
          // string, which is what we want for both: the app records no audio and
          // never opens the camera.
          cameraPermission: false,
          microphonePermission: false
        }
      ],
      // Required by expo-web-browser v15+ (config plugin sets up the native
      // browser-session support used by the legacy Google auth fallback flow).
      "expo-web-browser",
      [
        "expo-notifications",
        {
          // Android draws a notification's small icon from its alpha channel
          // alone, so a transparent-background silhouette of the brand mark is
          // the right shape. Not adaptive-icon-monochrome directly though: that
          // asset reserves adaptive-icon mask safe-zone padding (glyph fills only
          // the center ~55% of its 1024x1024 canvas), which made the status-bar
          // icon render tiny. This is the same silhouette re-cropped tight to its
          // glyph bbox with a small uniform margin, so it fills the notification
          // icon's own bounds instead.
          icon: "./assets/notification-icon.png",
          // Tint applied behind that silhouette - brandPrimary, matching
          // colorTokens.light.brandPrimary in src/theme/tokens.js. Hardcoded
          // because this file is build config, evaluated long before any theme
          // module is loadable, and the value is mode-independent here anyway.
          color: "#1B4DFF"
        }
      ],
      // Required by expo-secure-store v15+ (config plugin sets Android's
      // faceIDPermission / no-op iOS entries; no custom options needed here).
      "expo-secure-store",
      // APK/AAB size: enables R8 code shrinking + resource shrinking on every Android
      // release build (preview APK and production AAB alike - neither was minified
      // before), and restricts native libs to arm64-v8a on internal-test builds only
      // (see isInternalTestBuild above).
      [
        "expo-build-properties",
        {
          android: {
            enableProguardInReleaseBuilds: true,
            enableShrinkResourcesInReleaseBuilds: true,
            ...(isInternalTestBuild ? { buildArchs: ["arm64-v8a"] } : {})
          }
        }
      ]
    ],
    // EXPO_PUBLIC_-prefixed vars are inlined directly into the JS bundle at build time
    // (see src/config/api.js, which reads process.env.EXPO_PUBLIC_* directly) - mirroring
    // them into `extra` as well makes them visible in `expo config` / EAS build logs /
    // the build manifest for debugging, without adding a second runtime access path.
    extra: {
      apiUrl: process.env.EXPO_PUBLIC_API_URL,
      googleWebClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
      googleIosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
      googleAndroidClientId: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,
      useNativeGoogleAuth: process.env.EXPO_PUBLIC_USE_NATIVE_GOOGLE_AUTH,
      webBaseUrl: process.env.EXPO_PUBLIC_WEB_BASE_URL,
      eas: {
        // @mafnacer/mafqoudat - created via `eas init`:
        // https://expo.dev/accounts/mafnacer/projects/mafqoudat
        projectId: "0af1537e-6e29-4127-badc-c7f16884e198"
      }
    },
    scheme: "mafqoudat"
  }
};
